### ISSUE TITLE
unable to send any commands

### ISSUE THREAD

**Issue by z0mb0funk** [gopro/OpenGoPro#204]
**Component**
What is the bug in?
- Tutorials

**Describe the bug**
After successfully completing Tutorial 1, I am unable to send any commands to any of my GoPros.

**To Reproduce**
Run any script other than ble_connect.py

**Expected behavior**
Varies. Right now I'm just trying to progress through the tutorials. Expected behavior is defined in Tutorial 2. I connect to the GoPro send the command, but never progress past "setting shutter to on" or "putting camera to sleep" (etc, I've tried all scripts)

**Screenshots**
![image](https://user-images.githubusercontent.com/107705360/177890381-f18eba0c-00f0-43fe-a067-18090b30c48b.png)
![image](https://user-images.githubusercontent.com/107705360/177890441-a10f8e48-1c03-4471-aa0f-0dd9b3318d01.png)

**Hardware**
- Camera: Hero9 - 01.72.70& Hero10 - 01.42.70. 
- macOS (intel chip)

**Additional context**

**Comment by z0mb0funk** [comment]
There are no timeouts or errors. It will just indefinitely sit at "sending command", even if I turn off the camera.

**Comment by tcamise-gpsw** [comment]
It is because you have put the camera to sleep.

**Comment by z0mb0funk** [comment]
The second screenshot is an example of that command being tested. If you look at the first you'll see another example. I tried every example in the wiki and got the same result. It isn't because I'm putting the camera to sleep. The camera should send a response to ack the command and that isn't happening here.

**Comment by tcamise-gpsw** [comment]
Sorry I was reading the log incorrectly.

I am able to replicate this (only on Mac). The solution is to add a `response=True` parameter to all of the `write_gatt_char` method calls. This is a nasty little bug that happened when the bleak version got upgraded which updated the default value of this argument only on Mac.

I have a branch where I am working on fixing this. I'm also going to remove the open-gopro Python module dependency since upgrading this has the side effect of upgrading the bleak version.

**Comment by tcamise-gpsw** [comment]
This should be working now but let me know if there are any problems

**Comment by z0mb0funk** [comment]
Seems to be working as intended now. I just downloaded the new tutorial files and it works as described on the tutorial. Thanks for making the changes!
