### ISSUE TITLE
Open gopro for raspberry pi ?

### ISSUE THREAD

**Issue by roberto1963** [gopro/OpenGoPro#26]
Hello , 
I would like to control a gopro hero9 with bluetooth and a raspberry Pi.
I have install open gopro on a Raspberry Pi3+ .
I have follow instructions of https://gopro.github.io/OpenGoPro/python_sdk/  (but with pip3 instead of pip) . 
But I am unable to use it.
Raspberry Pi python3 version is only Python 3.7.3  (not 3.8) .   Is it a problem ?
Has anyone tried open gopro with a raspberry pi ? 
Thanks.
Roberto.

**Comment by tcamise-gpsw** [comment]
Hello. Yes, you do need the correct python version: 3.8.x. 

Other than that, the python SDK has limited testing on Linux. I have seen at least one bug in the bleak driver where it can not pair. In order to get around this, I had to manually connect and pair first using BlueZ from the command. After that, the python SDK does work as expected.

I started a [discussion ](https://github.com/hbldh/bleak/discussions/503) about this on the bleak repo but haven't gotten around to filing an issue / debugging it more yet.

I haven't tested this in months so perhaps it is fixed now. In any case, I encourage you to give it a try and report your findings 👍 

For now, I'll leave this ticket open as way to track (and improve) general Linux stability for the python SDK.
