### ISSUE TITLE
128 bit version for service id "FEA6"

### ISSUE THREAD

**Issue by sultanmyrza** [gopro/OpenGoPro#37]
I use ionic and run on android.
To connect to goPro bluetooth I use this packet 

In code I connect like this
```javascript
await BleClient.requestLEScan(
        { services: ["FEA6"], allowDuplicates: false },
        (result) => doSomethingWithResult(result)
      );
```
### on android I got this error
```
V/Capacitor: callback: 74973120, pluginId: BluetoothLe, methodName: requestLEScan, methodData: {"services":["FEA6"],"allowDuplicates":false}
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"74973120","pluginId":"BluetoothLe","methodName":"requestLEScan","success":false,"error":{"message":"Invalid service UUID."}}
```
But If I don't specify service id aka (it connects fine)
```javascript
await BleClient.requestLEScan(
        { services: [], allowDuplicates: false },
        (result) => doSomethingWithResutl(result)
      );
```
## But still want to know is there such thing? 128 bit version for GoPro service id "FEA6" 😅

**Comment by tcamise-gpsw** [comment]
Hello. The "Control and Query" service UUID is 0xFEA6 which is a 16-bit UUID. It is not possible to refer to this UUID as as 128-bit UUID. Note that UUID's in Bluetooth can either be 16 or 128 bits so this is acceptable behavior.

I've never used Ionic but I found [this](https://ionicframework.com/docs/native/ble#uuids) after a quick search:
"UUIDs are always strings and not numbers. Some 16-bit UUIDs, such as '2220' look like integers, but they're not. (The integer 2220 is 0x8AC in hex.) This isn't a problem with 128 bit UUIDs since they look like strings 82b9e6e1-593a-456f-be9b-9215160ebcac. All 16-bit UUIDs should also be passed to methods as strings."

So it seems that there might be some special handling needed for non-128 bit UUID's.
