### ISSUE TITLE
OpenGoPro command response documentation incomplete

### ISSUE THREAD

**Issue by aaramirez-g** [gopro/OpenGoPro#521]
What is the bug in?
- Documentation

**Describe the bug**
The new OpenGoPro BLE documentation is missing the Command Response Error codes that were present in the previous version. For example the Set [AP Control](https://gopro.github.io/OpenGoPro/ble/features/control.html#set-ap-control) response link just points to (https://gopro.github.io/OpenGoPro/ble/protocol/ble_setup.html#ble-characteristics) which does not give any details on what the response is. 

Previous Version: https://github.com/gopro/OpenGoPro/blob/90e8965f36f0233f17768e0ca04f9a17e5b5136a/docs/specs/ble_versions/ble_2_0.md#command-response

**Screenshots**
![openGoPro](https://github.com/gopro/OpenGoPro/assets/156131710/7853a786-c0fb-48fa-a9b7-64135f26dce7)

**Comment by tcamise-gpsw** [comment]
good catch. I'll add these back in

**Comment by tcamise-gpsw** [comment]
I've added the table of Command Statuses to the [Command TLV documentation](https://gopro.github.io/OpenGoPro/ble/protocol/data_protocol.html#commands).

Since these are common to all TLV Commands, they are not documented in each command. The idea is that you click on the TLV Type, i.e. TLV Command for "Set AP Control":

![image](https://github.com/gopro/OpenGoPro/assets/76070353/928d08d8-1871-44b9-82e3-7debb74c1cc6)


to then see this common information.
